# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationdentSize: 4
  ParameterListWrapping:
    active: false
empty-blocks:
  EmptyFunctionBlock:
    active: false
